services:
  khulnasoft-console:
    build:
      context: .
      dockerfile: Dockerfile
    # image: khulnasoft-console:latest
    container_name: khulnasoft-console
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - API_URL=${API_URL:-http://localhost:3000}
